spring:
  application:
    name: streaming-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    streams:
      application-id: outbox-streaming
      properties:
        processing.guarantee: exactly_once_v2
  config:
    import: optional:file:.env.sample[.properties]

app:
  kafka-topics:
    outbox-topic:
      name: jdmik12.streaming.command
      partitions: 3
      replicas: 3
      min-in-sync-replicas: 2
    cv-topic:
      name: jdmik12.cv.create
    accounting-topic:
      name: jdmik12.accounting.allocation.command
    security-topic:
      name: jdmik12.security.check.command
    notification-topic:
      name: jdmik12.notification.send.command
    dlt-topic:
      name: jdmik12.streaming.dlt
